### ISSUE TITLE
Latest UI feedback 13 sep 2011 (Anemometer Wind Logging Software)

### ISSUE THREAD

**Issue by baranidesign** [wind101net/atmo#1]
1.  Please rename the Download Data to "Download Logger Data"  the button should preform a quick download based on previous settings from the last date of imported data in the database. 
2.  Allow changing the path in the "Download Logger Data" dialog C:\Users\Janko\Documents\My Dropbox\Anemometer\Sensor Data\Parents Backyard
3.  When you select the Weibull range, is it possible to scale the histogram X-axis to the selected range?
4.  Weibull slider upper limit is not affecting the curve fit...lower limit is affecting it fine.
5.  Is it possible to select 0.5 increments on the slider?  you can decrease the max value range to 70 (or if calculated in m/s to 20m/s)
6.  How come the historical data plot is a bar graph when 12weeks or higher time range is selected?  
7.  Is it possible to plot the standard deviation as a line graph on top of the 10min averages in 12
8.  The reverse date order of historical graphs is very confusing...can you change it to chronological order?
9.  Rename PWS Status to "WWW Streaming Status"?  or something more intuitive.

**Comment by aarondandy** [comment]
1. Done
2. working
3. working
4. investigating
5. will try
6. the graph clumps stuff like that sometimes, will investigate
7. can look into it
8. working
9. Web Streaming Status?

**Comment by baranidesign** [comment]
point 9. =  yes :-)

**Comment by aarondandy** [comment]
1. Done
2. Done
3. Moved
4. Closed (It does but only slightly. I think it is correct.)
5. Done (only supports increments of 1)
6. Moved: the graph clumps stuff like that sometimes, will investigate
7. can look into it
8. Done
9. Done (Web Streaming Status)
