### ISSUE TITLE
Calculator for computing Wind Direction North Calibration value

### ISSUE THREAD

**Issue by baranidesign** [wind101net/atmo#10]
Add this calculator to the Update Firmware dialog right under the Get Command.  

It computes the bit offset that the user has to input to set the initial zero direction vane direction.

**Comment by aarondandy** [comment]
You have a picture or detailed description for this?

**Comment by baranidesign** [comment]
Yes, please see http://www.baranidesign.com/direction-vane-calibration-calculator.html
I will email you the spreadsheet so that you can see the calculator.

**Comment by aarondandy** [comment]
I lifted the equation from the javascript.

**Comment by aarondandy** [comment]
I don't have the hardware to test this but am pretty sure I got it right. Can re-open later if I did not.

**Comment by baranidesign** [comment]
If the calculated value is equal to this calculator, than you are good to
go.   http://www.baranidesign.com/direction-vane-calibration-calculator.html

It should then change the 1st number in the correction factor string for
the anemometer and apply the change and give a popup confirmation whether
applying the correction factor change was successful.

---

On Fri, Jan 27, 2012 at 07:37, Aaron Dandy <
reply@reply.github.com
