### ISSUE TITLE
GET command should send Reset after getting values

### ISSUE THREAD

**Issue by baranidesign** [wind101net/atmo#17]
When GET button is pressed, anemometer enters Boot loader mode via **0x74** (send enter Boot Mode to anemometer from PC)  command.  
Next the **0x71** (send Correction Factors to PC) command is executed.
**MISSING:**  **0x76** (send Reset command to anemometer) **SHOULD BE SENT TO RESET ANEMOMETER OUT OF BOOT LOADER MODE.**

**Comment by aarondandy** [comment]
I am positive I am sending 0x76, perhaps the anem isn't getting message. I changed it to send 3 times, hopefully one of them gets there. I have noticed that often with certain commands packs must be sent multiple times.

**Comment by baranidesign** [comment]
Good idea with sending the reset 3 times. This issue was feedback I got from the electrical hardware engineer from his recent testing. It may be the case that the command wasn't getting through sometimes, just like you mention.

**Comment by baranidesign** [comment]
Electrical Engineer was monitoring the connections and mentioned that he did
not see the command get sent...I sent him the latest installer today, so
hopefully he we report back positively :-)

---

**Comment by aarondandy** [comment]
What is the current story with the firmware? What do I have on my
anem/daq and what will the 2nd anem have?

On Fri, Sep 23, 2011 at 9:24 AM, Jan Barani
reply@reply.github.com
wrote:

> Electrical Engineer was monitoring the connections and mentioned that he did
> not see the command get sent...I sent him the latest installer today, so
> hopefully he we report back positively :-)
> 
> ---
> 
> On Tue, Sep 20, 2011 at 04:55, Aaron Dandy <

**Comment by baranidesign** [comment]
The anems will have the old firmware...the new one should be finished
wednesday...._The only thing that should change from you end is that the
anemometers will send out N/A for humidity/pressure/temp sensors that do not
exist._  Otherwise, the DAQ firmware is not changing...its still the same.

## _Edo please confirm this, and correct it if I'm wrong._
