### ISSUE TITLE
Live Plots display of data is Mixed up when multiple Anemometers are connected

### ISSUE THREAD

**Issue by baranidesign** [wind101net/atmo#18]
ERROR:  When 2 anemometers are connected, and **Anemometer A is selected**, live data plots show anemometer B data.
ERROR:  When 2 anemometers are connected, and **Anemometer B is selected**, live data plots show anemometer A data.
CORRECT:  When 2 anemometers are connected, and **Neither Anemometer A nor B** are selected, live data plots show no data.

**Comment by aarondandy** [comment]
Are you sure the NIDs are assigned as you expect? It is possible they are not, the NID assignment process is not exactly simple as it is not managed by the hardware.

**Comment by baranidesign** [comment]
I will have another aneometer sent to you so that you can test properly.
 Please expect them at the end of next week.

---

BARANI DESIGN
525 Nelson Rising Ln. #909, San Francisco CA 94158 USA
Dubová 495/11, 031 04 Liptovský Mikuláš, SK
Tel USA: +1-619-573-9463     Fax: +1-925-905-4142

## jan@baranidesign.com          http://www.baranidesign.com

**Comment by baranidesign** [comment]
Please expect 3 anemometers to arrive this week.
