### ISSUE TITLE
Web Streaming erroneous rain & pressure data

### ISSUE THREAD

**Issue by baranidesign** [wind101net/atmo#2]
Please double check rainfall and barometric pressure readings as they get sent out to Weather underground.  
On their live data widget, I see -2537.13 cm of rain and -33829.1 m as pressure.

**Comment by aarondandy** [comment]
Works fine for me. Get me some more details. Can you get a screenshot my way perhaps? The rainfall will have a value but for me it is -99.99in, its just how PWS seems to work... The pressure works great for me though.
