### ISSUE TITLE
Latest installer feedback.

### ISSUE THREAD

**Issue by baranidesign** [wind101net/atmo#20]
1.  Under Preferences/Data/   rename "Sunch Data Logger Clock"   Autosynch Data Logger Clock"
2.  Synch Logger Time popup after clicking Synch Logger time word "TIme"  should be "Time"  ...I should no be capitalized.
3.  Splash screen is the old Atmo 1.0 spash screen....fix to the new
4.  Help/About menu Splash screen should match the program start splash screen.
5.  For the BETA test, please make the splash screens the Atmo Barani design splash screens.
6.  Remove the redundant Logger Time Synch menu item from the Tools Menu. since you added the Auto time synch into the preferences.

**Comment by aarondandy** [comment]
1. Auto sync data logger clock
2. Sync logger time
3. The installer does not currently deploy the splash screen. It should be a blank screen currently. You may have leftover image files from testing in your Atmo program folder.
4. Yup
5. OK
6. Done
