### ISSUE TITLE
Delete Source Files in Import Dialog...do the files get backed up?

### ISSUE THREAD

**Issue by baranidesign** [wind101net/atmo#22]
Does the Delete Source Files in Import Dialog delete and backup the source files?  
or
Does it just delete them?

**It should back them up on the hard drive in a folder under My Documents**

**Comment by baranidesign** [comment]
Please rename "Backup Logger Data and Clean SD Card / Keep SD Card Clean"  or something similar....Please give feedback.

**Comment by aarondandy** [comment]
I only delete if the check box was checked, only if the file was copied (what if you opened the file form my documents?) and only the source of the copy (SD card).

**Comment by aarondandy** [comment]
Backup logger data and delete imported files from source (SD card).
