### ISSUE TITLE
TIME CORRECTION ALGORITHM

### ISSUE THREAD

**Issue by baranidesign** [wind101net/atmo#26]
If the data logger time resets due to a power outage, the real time clock will skip back in time to Mar15 2010 or some past date and continue to collect data.   Since you know when the reset happened by the last data with a correct date, and you know when you also know when you synchronized the clock again the first time after reset by when data with the correct date starts again...basically you can see a gap in data with the correct time...you can calculate the time gap length and then take the data from Mar15 2010 and paste it into the gap in the data with the correct date.  

**INPUTS:**
Start Date of data with wrong time stamp.
Start Date of time gap in good data
End Date of time gap in good data

**PROCEDURE:**
*_1.  *_Match the Start date & time of data with wrong time stamp To the Start date and time of the time gap 
*_2.  *_Then fill in the wrong time stamp data as far as you can into the time gap.
*_3.  *_If there is less wrong time stamp data than the time gap, then a short time gap will still exist in the corrected data....basically if the power outage was long.
*_4.  *_If there is more wrong time stamp data than the time gap, then the extra wrong time stamp data should Not overwrite the good time stamp data and the overwriting/filling in of data should end at the End Date of the time gap in good data.

**Comment by aarondandy** [comment]
when a file is imported, those time readings that are in the file with invalid dates are extrapolated backwards from the first correct date found during import. that is how we have taken care of that in the past. I have made changes to the database operations to allow a user to better perform the data manipulation operations. The way it currently works is the UI allows a user to select a time range of data and re-map that range to what they feel is correct. I feel the current UI is simpler to understand than this as there is no need to calculate time gaps for example, you just specify two date ranges.

**Comment by aarondandy** [comment]
The purpose of this feature was to correct the data in the event that logger and computer time had drifted too far.
