### ISSUE TITLE
Database time correction- NOT Functioning

### ISSUE THREAD

**Issue by baranidesign** [wind101net/atmo#30]
Applying database time correction does not cause a crash, but also does NOT do anything....

It may be a good idea to implement it in a way that:   **When the correction is applied**, the **old database is NOT affected**, but a  **COPY of the Original with the Correction Applied is created**.

**Comment by aarondandy** [comment]
I don't understand this issue, call me sometime.

**Comment by aarondandy** [comment]
I will reopen a new issue for this due to our chat
