### ISSUE TITLE
Firmware update does not work!!!

### ISSUE THREAD

**Issue by baranidesign** [wind101net/atmo#31]
Please try the firmware update dialog.  It is not working to update anemometers.  Please see the latest firmware in the email.  Atmo 1.0 updates just fine with the newest firmware.

**Comment by aarondandy** [comment]
Could you please provide more details. For example:

Which anemometer were you using? (has wind direction?)
Which firmware version is currently on the anemometer before attempting to upgrade the firmware?
Is the anemometer currently assigned a letter or unassigned?

**Comment by aarondandy** [comment]
I have only been able to reproduce any issues with updating the firmware once so far. Re applying power to the DAQ corrected that issue. My best guess is that on a rare occasion the reset command is not making it through to the DAQ. How often are you seeing this behavior?

**Comment by aarondandy** [comment]
I believe I have determined what conditions are required to cause this issue, if not this is a different issue. I am unable to update an anem that is currently not assigned. If the anem is assigned to A,B,C, or D it works fine. It appears to be an issue with the software, probably something embarrassing I bet. Working on it...
