### ISSUE TITLE
10min Average and StDev Data calculation is Incorrect

### ISSUE THREAD

**Issue by baranidesign** [wind101net/atmo#35]
When I exported the Raw Data and 10min average data for analysis in Excel:
1.  The 10min Averages as calculated in Excel did not match the Raw Exported 1sec Anemometer data.
2.  Temperature Standard Deviation is not Calculated at all.

**Comment by aarondandy** [comment]
I cannot reproduce this. Everything looks fine to me.
- Are you counting the 10 minute period correctly? Ex for a time stamp starting at 10:32.15 AM are you counting the period as 10:32.15-10:39.59 or as 10:32.15-10:40.15? It should be the prior.
- Try looking at the CSV file in a text editor to see if Microsoft Excel is displaying the value correctly.
- Try to provide me the input data, parameters, and if possible .csv output you have.

**Comment by aarondandy** [comment]
I found an issue that would cause 10 minute summaries to become out of sync with the raw data. I feel strongly that this would be the cause of the inconsistency you witnessed in this issue. If the next version does not correct this, please reopen this issue with more details.

**Comment by baranidesign** [comment]
Great...I can't wait to see your work of art finally working properly ;-)  If you need me to set a fix, send me a installer so that I can debug for you as you make progress.  People like the UI very much...now lets debug it properly before Beta 2 release.
