### ISSUE TITLE
Weibull 

### ISSUE THREAD

**Issue by baranidesign** [wind101net/atmo#39]
Let the slider min value go to zero, but in the weibul calculation, all zero wind speeds should be treated as wind speed 0.25m/s    Also the histogram should show how often zero wind speed occurs by having a bar at zero.   If the database treats zero wind speed and No-data (when logger was turned off) the same, that is very bad and needs to be fixed.

OBSOLETE---
Weibull default min value should be 0.5m/s even if the slider is set at zero.    Right now it seems like its zero and its causing eroneous Weibull estimate...compare the Weibull Mean versus the Regular Mean wind speed value.

**Comment by aarondandy** [comment]
I am seeing a very different effect. When I exclude 0 values from the calculation the W-Mean and Mean diverge greatly from one another. Can you give me some more details on what you are seeing like values or a screen shot?

If you are only seeing a slight difference:
There will be a slight difference between the Mean and W-Mean because computers have finite precision, even if the algorithm is 100% correct. This is especially true when calculating these values for millions of records, all of which are themselves averages representing tens of millions of records... for just a couple of months.

**Comment by baranidesign** [comment]
Where you may be going wrong with the Weibull calculation is if the Data
Base doesn't differentiate between when data logger was turned off an
NO-DATA was collected and when data was collected but wind Speed was
zero....if it does this, this is a major issue that needs to be addressed
in the database.  The attached picture shows with a blue line what the
Weibull curve fit should look like for the data being shown.

TO QUANLIFY MY ABOVE STATEMENT:

Is database is treating NO-DATA and ZERO-DATA the same in the Database
since there is no Blue Bar for Zero wind speed values?   What this means is
that the database is making up zero wind speed data, _OR there is a lot of
Zero wind speed data which is just not showing up on the Blue bar histogram_.
  So either the data base or the histogram need to be fixed.  \*  Play with
the 99999 value in the spreadsheet and try make the curvefits.*

_IMPORTANT:_
- Also, in the Weibull _calculation_, can you please change the lowest
  wind speed\* to 0.25 from 0.001.\*  This will make the curve look a lot
  better if there is a lot of zero wind speed data. (This is not the lowest
  wind speed shown in the graph, but the _"zero" wind speed used in the
  curve fit calculation_....let me know if you know what I mean)
- Also, as I mentioned, to verify that everything is working like it
  should, that *script to create .DAT files from .CSV files is
  important. \* Please
  let me know if you started on it.

## Anemometer http://www.baranidesign.com/anemometer.html

**Comment by baranidesign** [comment]
Where you may be going wrong with the Weibull calculation is if the Data Base doesn't differentiate between when data logger was turned off an NO-DATA was collected and when data was collected but wind Speed was zero....if it does this, this is a major issue that needs to be addressed in the database.  The attached picture shows with a blue line what the Weibull curve fit should look like for the data being shown.

TO QUANLIFY MY ABOVE STATEMENT:

Is database is treating NO-DATA and ZERO-DATA the same in the Database since there is no Blue Bar for Zero wind speed values?   What this means is that the database is making up zero wind speed data, **OR** there is a lot of Zero wind speed data which is just not showing up on the Blue bar histogram.   So either the data base or the histogram need to be fixed.    Play with the 99999 value in the spreadsheet and try make the curvefits.

**IMPORTANT:**
1.  Also, in the Weibull calculation, can you please change the lowest wind speed **to 0.25** from 0.001.  This will make the curve look a lot better if there is a lot of zero wind speed data. (This is not the lowest wind speed shown in the graph, but the **"zero" wind speed used in the curve fit calculation**....let me know if you know what I mean)
2.  Also, as I mentioned, to verify that everything is working like it should, that **script to create .DAT files from .CSV files** is important.  Please let me know if you started on it.

**Comment by aarondandy** [comment]
1. "all zero wind speeds should be treated as wind speed 0.25m/s" - My concern with this is that the data will not be correct. Garbage in, garbage out and all that.
2. "Also the histogram should show how often zero wind speed occurs by having a bar at zero": if I do that we will be unable to see the histogram values for when there is wind. It would be a graph showing 1000 units vs 1 unit, they will just appear as thin lines.
3. Nil data and zero data are very different and are treated as such, I even keep counts of the records when aggregating. nil data is not counted. 
4. For the DAT/CSV converter I closed the issue for it (https://github.com/wind101net/atmo/issues/12) and should be in your hands soon.
5. "can you please change the lowest wind speed\* to 0.25 from 0.001" - I will investigate this. You just mean, treat all 0 values as 0.001?

**Comment by baranidesign** [comment]
1.  The reason for this is that the anemometer minimum recorded wind speed is appx. 0.5m/s and the likelyhood of absolutely zero (0) wind speed is very small.  That is why, I want to take the average value 0.25 between 0 and 0.5m/s as it will be more accurate than 0.  In a real application, not in one of our rooms, the wind data will have very little 0-0.5m/s wind speeds, but it is important to show the amount of time that this happens, thus a bor for this should be included in the histogram.
2.  If the anemometer is in an outdoor location, the zero bar (0-0.5m/s) will not be very big. Its mostly a problem when testing indoors.
3.  GREAT!  :-)
4.  GREAT!  :-)
5.  Treat all 0 zero data values as 0.25 m/s

**Comment by aarondandy** [comment]
Okay your logic on the low frequencies of 0 values sounds ... sound.
