### ISSUE TITLE
Atmo doesn't show DAQ is connected with Turkish Regional Settings

### ISSUE THREAD

**Issue by baranidesign** [wind101net/atmo#40]
Upon connecting DAQ to computer, SD card would show up in Windows, but the logger or anemometers would not show up...the logger time did not show up either.
**_CAUSE/FIX:**_
We just changed the regional settings from Turkish to English and than every thing is ok.

**Comment by aarondandy** [comment]
1. Need to see if I can reproduce this by setting my language to that
2. Need to see if I can fix it by changing the text encoding rules.

**Comment by aarondandy** [comment]
Root of the problem appears to be that "Atmo.Daq.Win32.PicHidUsbConnection.FindDevicePath()" is complete dookie. It needs to:
1. match the thread culture as the usage of Encoding.Unicode.GetString(,,) is probably wrong.
2. be re-factored for sure.
3. be called less often, as it is slow!

**Comment by aarondandy** [comment]
I think I may have fixed this but I don't currently have a way to test it. It is not just an issue with Turkish (although I found a separate issue that is) but is an issue with Turkish on older versions of Windows. Can you confirm if this person was using windows XP? I will keep working this issue with that assumption.

**Comment by baranidesign** [comment]
He was using windows 7 Professional 64bit...please make a build and i will have him test it.

**Comment by aarondandy** [comment]
I did change the part that I thought may cause this issue, but when I changed my Win7 x64 to Turkish I had no problem tp begin with so I am not certain this will fix it, but I don't have anything else to go on. I do however have an EN build of windows, maybe that is the difference...

**Comment by baranidesign** [comment]
Turkish issues are fixed...now Atmo 2 powered anemometers can spin anywhere

## in the world :-)

On Sat, Nov 26, 2011 at 19:41, Aaron Dandy <
reply@reply.github.com

**Comment by baranidesign** [comment]
Aaron,
Can you just give me an update as to when you could have the next beta
release.
Thank you,
Jan
