### ISSUE TITLE
Long term live data is too slow

### ISSUE THREAD

**Issue by aarondandy** [wind101net/atmo#41]
Live data appears faulty after running for an extended period of time.
1. Changing the display time span range does not operate as expected (details are not yet known)
2. The actual time does appear to be in sync according to a screenshot of the issue.

**Comment by aarondandy** [comment]
To test this I am considering adding an operation that would generate a nights worth of random data for n sensors. Should be the only way to reproduce this as the DAQ communication will not hang the system. It must be something to do with the display of the graphs.

**Comment by baranidesign** [comment]
Have you been able to make progress on this issue?  Can you use the anemometer wind data generator you created for Atmo 1.0 demo to test this?
