### ISSUE TITLE
Atmo does not see files created with: AtmoDataConvert.exe 

### ISSUE THREAD

**Issue by baranidesign** [wind101net/atmo#43]
Atmo does not see files created with: AtmoDataConvert.exe
As a result, I cannot import them into atmo to test anemometer data integrity.

**Comment by aarondandy** [comment]
I need you to send me one of these files. Did you rename the file?

**Comment by aarondandy** [comment]
I am going to leave this one open but remove it from the milestone until there are more details.

**Comment by aarondandy** [comment]
I believe this to be related to invalid data files, the file name was not in the correct format.

**Comment by baranidesign** [comment]
I did try renaming the file.

---

BARANI DESIGN
525 Nelson Rising Ln. #909, San Francisco CA 94158 USA
Dubová 495/11, 031 04 Liptovský Mikuláš, SK
Tel USA: +1-619-573-9463     Fax: +1-925-905-4142

## jan@baranidesign.com          http://www.baranidesign.com

On Fri, Jan 27, 2012 at 07:36, Aaron Dandy <
reply@reply.github.com
