### ISSUE TITLE
Atmo 2.0 beta 2 crash on startup after working for 2 days

### ISSUE THREAD

**Issue by baranidesign** [wind101net/atmo#46]
Description:
  Stopped working

Problem signature:
  Problem Event Name:   CLR20r3
  Problem Signature 01: atmo.ui.devex.exe
  Problem Signature 02: 2.0.4411.32997
  Problem Signature 03: 4f25d41a
  Problem Signature 04: System.Data.SQLite
  Problem Signature 05: 1.0.74.0
  Problem Signature 06: 4e106e2b
  Problem Signature 07: 7e
  Problem Signature 08: 84
  Problem Signature 09: System.Data.SQLite.SQLite
  OS Version:   6.1.7600.2.0.0.768.3
  Locale ID:    1033

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

**Comment by aarondandy** [comment]
Any answers to these questions will help:

Was it just running, as usual, without user interaction?
Were you taking an action to cause this error?
Is there an entry in the Event log around that same time with exception data?
Can I see the data?
Is there database corrupted?
Can you reproduce this in any way, less than two days?

**Comment by baranidesign** [comment]
I uninstalled Atmo2 and reinstalled it and the same error seems to be occurring.  Every time I restart I get this crash. but atmo is still working and I can use it...just the crash window shows up.....

Though now as I type I tried it again and Atmo is completely grayed out.  I will email my install folder to you.

Description:
  Stopped working

Problem signature:
  Problem Event Name:   CLR20r3
  Problem Signature 01: atmo.ui.devex.exe
  Problem Signature 02: 2.0.4411.32997
  Problem Signature 03: 4f25d41a
  Problem Signature 04: System.Data.SQLite
  Problem Signature 05: 1.0.74.0
  Problem Signature 06: 4e106e2b
  Problem Signature 07: 7e
  Problem Signature 08: 84
  Problem Signature 09: System.Data.SQLite.SQLite
  OS Version:   6.1.7600.2.0.0.768.3
  Locale ID:    1033

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
