### ISSUE TITLE
Missing SD card data while PC running. 

### ISSUE THREAD

**Issue by djwiktor** [wind101net/atmo#58]
After long time test of ATMO II & anemometer first version, data on SD card are not written by DAQ, when PC is powered on. 
See open doc file https://docs.google.com/present/edit?id=0AVDfwwIDRG73ZGN3bjRudjdfNDM2cXBkOGc0 on the end of presentation.  Already tested with PC and Notebook. Same results > If Computer is turned ON, data are not writted to SD card, until the PC is shutdown.

**Comment by aarondandy** [comment]
You may want to make sure that this is not as a result of Windows not refreshing the file system. While keeping the unit powered on, disconnect it from the Windows PC and reconnect it. After doing this see if the data had actually been written after all.

**Comment by djwiktor** [comment]
After problem researching, mainly seems to be a defective Anemo/DAq unit, as after unit change, data on second unit are OK, streaming enabled, no Windows missing data issue found. Second unit is working correctly.

**Comment by aarondandy** [comment]
It is believed to be an issue with that unit.
