### ISSUE TITLE
Database write permission error in Windows 7 

### ISSUE THREAD

**Issue by baranidesign** [wind101net/atmo#60]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.Data.SQLite.SQLiteException: Attempt to write a read-only database
attempt to write a readonly database
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at Atmo.Data.DbDataStore.AddSensor(ISensorInfo sensor)
   at Atmo.UI.DevEx.ImportDataForm.GetOrAddSensor(ImportAnemMap map)
   at Atmo.UI.DevEx.ImportDataForm.<buttonImport_Click>b__1a(ImportAnemMap map)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.Queue`1..ctor(IEnumerable`1 collection)
   at Atmo.UI.DevEx.ImportDataForm.ImportDataProcesser..ctor(IEnumerable`1 sets, Boolean delSource, Boolean recordOverwrite, IDataStore dataStore)
   at Atmo.UI.DevEx.ImportDataForm.buttonImport_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at DevExpress.XtraEditors.BaseButton.OnClick(EventArgs e)
   at DevExpress.XtraEditors.BaseButton.OnMouseUp(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.Utils.Controls.ControlBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5448 (Win7SP1GDR.050727-5400)
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll

Atmo.UI.DevEx
    Assembly Version: 2.0.4411.32997
    Win32 Version: 2.0.4411.32997
##     CodeBase: file:///C:/Program%20Files/BaraniDesign/Atmo2/Atmo.UI.DevEx.exe

System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5446 (Win7SP1GDR.050727-5400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5453 (Win7SP1GDR.050727-5400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

DevExpress.Utils.v10.1
    Assembly Version: 10.1.7.0
    Win32 Version: 10.1.7.0
##     CodeBase: file:///C:/Program%20Files/BaraniDesign/Atmo2/DevExpress.Utils.v10.1.DLL

Atmo.UI.WinForms.Controls
    Assembly Version: 2.0.4411.32996
    Win32 Version: 2.0.4411.32996
##     CodeBase: file:///C:/Program%20Files/BaraniDesign/Atmo2/Atmo.UI.WinForms.Controls.DLL

Atmo.Core
    Assembly Version: 2.0.4411.32996
    Win32 Version: 2.0.4411.32996
##     CodeBase: file:///C:/Program%20Files/BaraniDesign/Atmo2/Atmo.Core.DLL

Atmo.Daq.Win32
    Assembly Version: 2.0.4411.32996
    Win32 Version: 2.0.4411.32996
##     CodeBase: file:///C:/Program%20Files/BaraniDesign/Atmo2/Atmo.Daq.Win32.DLL

System.Data.SQLite
    Assembly Version: 1.0.74.0
    Win32 Version: 1.0.74.0
##     CodeBase: file:///C:/Program%20Files/BaraniDesign/Atmo2/System.Data.SQLite.DLL

System.Data
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
##     CodeBase: file:///C:/Windows/assembly/GAC_32/System.Data/2.0.0.0__b77a5c561934e089/System.Data.dll

System.Transactions
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.4927 (NetFXspW7.050727-4900)
##     CodeBase: file:///C:/Windows/assembly/GAC_32/System.Transactions/2.0.0.0__b77a5c561934e089/System.Transactions.dll

DevExpress.XtraEditors.v10.1
    Assembly Version: 10.1.7.0
    Win32 Version: 10.1.7.0
##     CodeBase: file:///C:/Program%20Files/BaraniDesign/Atmo2/DevExpress.XtraEditors.v10.1.DLL

DevExpress.Data.v10.1
    Assembly Version: 10.1.7.0
    Win32 Version: 10.1.7.0
##     CodeBase: file:///C:/Program%20Files/BaraniDesign/Atmo2/DevExpress.Data.v10.1.DLL

System.Core
    Assembly Version: 3.5.0.0
    Win32 Version: 3.5.30729.5420 built by: Win7SP1
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll

DevExpress.XtraBars.v10.1
    Assembly Version: 10.1.7.0
    Win32 Version: 10.1.7.0
##     CodeBase: file:///C:/Program%20Files/BaraniDesign/Atmo2/DevExpress.XtraBars.v10.1.DLL

System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll

DevExpress.XtraCharts.v10.1
    Assembly Version: 10.1.7.0
    Win32 Version: 10.1.7.0
##     CodeBase: file:///C:/Program%20Files/BaraniDesign/Atmo2/DevExpress.XtraCharts.v10.1.DLL

DevExpress.Charts.v10.1.Core
    Assembly Version: 10.1.7.0
    Win32 Version: 10.1.7.0
##     CodeBase: file:///C:/Program%20Files/BaraniDesign/Atmo2/DevExpress.Charts.v10.1.Core.DLL

DevExpress.XtraCharts.v10.1.UI
    Assembly Version: 10.1.7.0
    Win32 Version: 10.1.7.0
##     CodeBase: file:///C:/Program%20Files/BaraniDesign/Atmo2/DevExpress.XtraCharts.v10.1.UI.DLL

System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

lq0_r8ho
    Assembly Version: 2.0.4411.32996
    Win32 Version: 2.0.50727.5453 (Win7SP1GDR.050727-5400)
##     CodeBase: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

System.EnterpriseServices
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.5420 (Win7SP1.050727-5400)
##     CodeBase: file:///C:/Windows/assembly/GAC_32/System.EnterpriseServices/2.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll

Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 2.0.50727.5448 (Win7SP1GDR.050727-5400)
##     CodeBase: file:///C:/Windows/assembly/GAC_32/mscorlib/2.0.0.0__b77a5c561934e089/mscorlib.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by baranidesign** [comment]
Another Windows 7 user in Peru reported this database write issue...see details below.

System.Data.SQLite.SQLiteException: Attempt to write a read-only database
attempt to write a readonly database
   en System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   en System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   en System.Data.SQLite.SQLiteDataReader.NextResult()
   en System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   en System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   en System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   en Atmo.Data.DbDataStore.AddSensor(ISensorInfo sensor)
   en Atmo.UI.DevEx.ImportDataForm.GetOrAddSensor(ImportAnemMap map)
   en Atmo.UI.DevEx.ImportDataForm.<buttonImport_Click>b__1a(ImportAnemMap map)
   en System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   en System.Collections.Generic.Queue`1..ctor(IEnumerable`1 collection)
   en Atmo.UI.DevEx.ImportDataForm.ImportDataProcesser..ctor(IEnumerable`1 sets, Boolean delSource, Boolean recordOverwrite, IDataStore dataStore)
   en Atmo.UI.DevEx.ImportDataForm.buttonImport_Click(Object sender, EventArgs e)
   en System.Windows.Forms.Control.OnClick(EventArgs e)
   en DevExpress.XtraEditors.BaseButton.OnClick(EventArgs e)
   en DevExpress.XtraEditors.BaseButton.OnMouseUp(MouseEventArgs e)
   en System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   en System.Windows.Forms.Control.WndProc(Message& m)
   en DevExpress.Utils.Controls.ControlBase.WndProc(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Ensamblados cargados **************
mscorlib
    Versión del ensamblado: 2.0.0.0
    Versión Win32: 2.0.50727.4963 (win7RTMGDR.050727-4900)

##     Código base: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll

Atmo.UI.DevEx
    Versión del ensamblado: 2.0.4348.27314
    Versión Win32: 2.0.4348.27314

##     Código base: file:///C:/Program%20Files/BaraniDesign/Atmo2/Atmo.UI.DevEx.exe

System.Windows.Forms
    Versión del ensamblado: 2.0.0.0
    Versión Win32: 2.0.50727.4961 (win7RTMGDR.050727-4900)

##     Código base: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Versión del ensamblado: 2.0.0.0
    Versión Win32: 2.0.50727.4968 (win7RTMGDR.050727-4900)

##     Código base: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Versión del ensamblado: 2.0.0.0
    Versión Win32: 2.0.50727.4927 (NetFXspW7.050727-4900)

##     Código base: file:///C:/Windows/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

DevExpress.Utils.v10.1
    Versión del ensamblado: 10.1.7.0
    Versión Win32: 10.1.7.0

##     Código base: file:///C:/Program%20Files/BaraniDesign/Atmo2/DevExpress.Utils.v10.1.DLL

Atmo.UI.WinForms.Controls
    Versión del ensamblado: 2.0.4348.27312
    Versión Win32: 2.0.4348.27312

##     Código base: file:///C:/Program%20Files/BaraniDesign/Atmo2/Atmo.UI.WinForms.Controls.DLL

Atmo.Core
    Versión del ensamblado: 2.0.4348.27312
    Versión Win32: 2.0.4348.27312

##     Código base: file:///C:/Program%20Files/BaraniDesign/Atmo2/Atmo.Core.DLL

Atmo.Daq.Win32
    Versión del ensamblado: 2.0.4348.27313
    Versión Win32: 2.0.4348.27313

##     Código base: file:///C:/Program%20Files/BaraniDesign/Atmo2/Atmo.Daq.Win32.DLL

System.Data.SQLite
    Versión del ensamblado: 1.0.74.0
    Versión Win32: 1.0.74.0

##     Código base: file:///C:/Program%20Files/BaraniDesign/Atmo2/System.Data.SQLite.DLL

System.Data
    Versión del ensamblado: 2.0.0.0
    Versión Win32: 2.0.50727.4927 (NetFXspW7.050727-4900)

##     Código base: file:///C:/Windows/assembly/GAC_32/System.Data/2.0.0.0__b77a5c561934e089/System.Data.dll

System.Transactions
    Versión del ensamblado: 2.0.0.0
    Versión Win32: 2.0.50727.4927 (NetFXspW7.050727-4900)

##     Código base: file:///C:/Windows/assembly/GAC_32/System.Transactions/2.0.0.0__b77a5c561934e089/System.Transactions.dll

DevExpress.XtraEditors.v10.1
    Versión del ensamblado: 10.1.7.0
    Versión Win32: 10.1.7.0

##     Código base: file:///C:/Program%20Files/BaraniDesign/Atmo2/DevExpress.XtraEditors.v10.1.DLL

DevExpress.Data.v10.1
    Versión del ensamblado: 10.1.7.0
    Versión Win32: 10.1.7.0

##     Código base: file:///C:/Program%20Files/BaraniDesign/Atmo2/DevExpress.Data.v10.1.DLL

System.Core
    Versión del ensamblado: 3.5.0.0
    Versión Win32: 3.5.30729.4926 built by: NetFXw7

##     Código base: file:///C:/Windows/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll

DevExpress.XtraBars.v10.1
    Versión del ensamblado: 10.1.7.0
    Versión Win32: 10.1.7.0

##     Código base: file:///C:/Program%20Files/BaraniDesign/Atmo2/DevExpress.XtraBars.v10.1.DLL

System.Xml
    Versión del ensamblado: 2.0.0.0
    Versión Win32: 2.0.50727.4927 (NetFXspW7.050727-4900)

##     Código base: file:///C:/Windows/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll

mscorlib.resources
    Versión del ensamblado: 2.0.0.0
    Versión Win32: 2.0.50727.4963 (win7RTMGDR.050727-4900)

##     Código base: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll

DevExpress.XtraCharts.v10.1
    Versión del ensamblado: 10.1.7.0
    Versión Win32: 10.1.7.0

##     Código base: file:///C:/Program%20Files/BaraniDesign/Atmo2/DevExpress.XtraCharts.v10.1.DLL

DevExpress.Charts.v10.1.Core
    Versión del ensamblado: 10.1.7.0
    Versión Win32: 10.1.7.0

##     Código base: file:///C:/Program%20Files/BaraniDesign/Atmo2/DevExpress.Charts.v10.1.Core.DLL

DevExpress.XtraCharts.v10.1.UI
    Versión del ensamblado: 10.1.7.0
    Versión Win32: 10.1.7.0

##     Código base: file:///C:/Program%20Files/BaraniDesign/Atmo2/DevExpress.XtraCharts.v10.1.UI.DLL

System.Configuration
    Versión del ensamblado: 2.0.0.0
    Versión Win32: 2.0.50727.4927 (NetFXspW7.050727-4900)

##     Código base: file:///C:/Windows/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

ctwn-kzq
    Versión del ensamblado: 2.0.4348.27312
    Versión Win32: 2.0.50727.4968 (win7RTMGDR.050727-4900)

##     Código base: file:///C:/Windows/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll

System.EnterpriseServices
    Versión del ensamblado: 2.0.0.0
    Versión Win32: 2.0.50727.4927 (NetFXspW7.050727-4900)

##     Código base: file:///C:/Windows/assembly/GAC_32/System.EnterpriseServices/2.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll

Anonymously Hosted DynamicMethods Assembly
    Versión del ensamblado: 0.0.0.0
    Versión Win32: 2.0.50727.4963 (win7RTMGDR.050727-4900)

##     Código base: file:///C:/Windows/assembly/GAC_32/mscorlib/2.0.0.0__b77a5c561934e089/mscorlib.dll

System.Windows.Forms.resources
    Versión del ensamblado: 2.0.0.0
    Versión Win32: 2.0.50727.4927 (NetFXspW7.050727-4900)

##     Código base: file:///C:/Windows/assembly/GAC_MSIL/System.Windows.Forms.resources/2.0.0.0_es_b77a5c561934e089/System.Windows.Forms.resources.dll

*************\* Depuración JIT **************
Para habilitar la depuración Just In Time (JIT), el archivo de configuración de esta
aplicación o equipo (machine.config) debe tener el
valor jitDebugging establecido en la sección system.windows.forms.
La aplicación también se debe compilar con la depuración
habilitada

Por ejemplo:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Cuando esté habilitada la depuración JIT, cualquier excepción no controlada
se enviará al depurador JIT registrado en el equipo
en lugar de controlarlo mediante el cuadro de diálogo.

**Comment by aarondandy** [comment]
This should be corrected in the next release. If the issue persists it should be opened as a new item as it should not be related to permissions.
