### ISSUE TITLE
Copy Data off the SD card into a folder in My Documents before importing

### ISSUE THREAD

**Issue by baranidesign** [wind101net/atmo#7]
+.  Copy Data off the SD card into a folder in My Documents before importing to clear the SD card and to speed import since the USB 1.0 connection to the DAQ is slow.  
+.  Make the option to clear the SD card after import user select-able...probably a good idea.
+. To Speed Import...first move (Cut/Paste) SD card Data to hard drive (to My Documents/Atmo Data/Raw Data) and then import from hardrive into data base. This will keep the SD card empty to speed data import over the slow USB connection.

**Comment by aarondandy** [comment]
Time to read off the card vs. time to COPY from the card + read the files ...

I think this may possible slow the whole process down but could reduce the time the SD card is in use. This will require a large change to how data is imported.
